### ISSUE TITLE
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by muxiddin19** [kaistmm/SlowFastSign#7]
Hello! Great work! I need some guidelines for solving the problem that occurred while running the code:
python main.py --device 0 --dataset phoenix2014 --loss-weights Slow=0.25 Fast=0.25 --work-dir ./work_dir/phoenix2014/

/home/muhiddin/SlowFastSign
preprocess.sh ./work_dir/phoenix2014_test/output-hypothesis-dev-conv.ctm ./work_dir/phoenix2014_test/tmp.ctm ./work_dir/phoenix2014_test/tmp2.ctm
2024. 08. 21. (수) 10:50:21 KST
Preprocess Finished.
WER_primary:  18.88%
WER_auxiliary:  0.00%
WAR:  0.00%
WDR:  0.00%
/home/muhiddin/SlowFastSign
preprocess.sh ./work_dir/phoenix2014_test/output-hypothesis-dev.ctm ./work_dir/phoenix2014_test/tmp.ctm ./work_dir/phoenix2014_test/tmp2.ctm
2024. 08. 21. (수) 10:50:21 KST
Preprocess Finished.
WER_primary:  17.98%
WER_auxiliary:  0.00%
WAR:  0.00%
WDR:  0.00%
WER_primary:  18.00%
WER_auxiliary:  18.92%
WAR:  2.20%
WDR:  1.28%
[ Wed Aug 21 10:50:22 2024 ] Epoch 6667, dev  17.98%
  0%|                                                           0%|▏                                                          1%|▍                                                          1%|▌                                                          1%|▊                                                          2%|█                                                          2%|█▏                                                         2%|█▍                                                         3%|█▌                                                         3%|█▋                                                         3%|█▉                                                         3%|██                                                         4%|██▎                                                        4%|██▍                                                        4%|██▊                                                        5%|██▉                                                        5%|███                                                        5%|███▏                                                       6%|███▍                                                       6%|███▌                                                       6%|███▉                                                       7%|████                                                       7%|████▏                                                      7%|████▍                                                      8%|████▌                                                      8%|████▉                                                      8%|█████                                                      9%|█████▏                                                     9%|█████▌                                                     9%|█████▌                                                    10%|█████▉                                                    10%|██████                                                    10%|██████                                                    10%|██████▍                                                   11%|██████▋                                                   11%|██████▉                                                   11%|███████                                                   12%|███████▎                                                  12%|███████▍                                                  12%|███████▍                                                  13%|███████▊                                                  13%|███████▊                                                  13%|████████                                                  14%|████████▏                                                 14%|████████▍                                                 14%|████████▊                                                 15%|█████████                                                 15%|█████████▎                                                15%|█████████▍                                                16%|█████████▋                                                16%|█████████▌                                                16%|██████████                                                17%|█████████▉                                                17%|██████████                                                17%|██████████▋                                               17%|██████████▊                                               18%|███████████                                               18%|███████████▏                                              18%|███████████▍                                              19%|███████████▌                                              19%|███████████▍                                              19%|███████████▌                                              20%|████████████▏                                             20%|████████████▍                                             20%|████████████▌                                             21%|████████████▍                                             21%|████████████▌                                             21%|█████████████▏                                            22%|█████████████▍                                            22%|█████████████▌                                            22%|█████████████▊                                            23%|█████████████▉                                            23%|█████████████▋                                            23%|██████████████▎                                           23%|██████████████▌                                           24%|██████████████▊                                           24%|██████████████▉                                           24%|███████████████▏                                          25%|███████████████▎                                          25%|███████████████▌                                          25%|███████████████▋                                          26%|███████████████▉                                          26%|████████████████▏                                         26%|███████████████▊                                          27%|████████████████                                          27%|████████████████▋                                         27%|████████████████▉                                         28%|█████████████████                                         28%|█████████████████▎                                        28%|█████████████████▌                                        29%|█████████████████▋                                        29%|█████████████████▉                                        29%|██████████████████                                        30%|██████████████████▎                                       30%|██████████████████▌                                       30%|██████████████████▋                                       30%|██████████████████▉                                       31%|███████████████████                                       31%|███████████████████▎                                      31%|███████████████████▍                                      32%|███████████████████▎                                      32%|███████████████████▌                                      32%|███████████████████▊                                      33%|███████████████████▉                                      33%|████████████████████▏                                     33%|████████████████████▎                                     34%|████████████████████▌                                     34%|████████████████████▋                                     34%|████████████████████▉                                     35%|█████████████████████                                     35%|█████████████████████▎                                    35%|█████████████████████▍                                    36%|█████████████████████▋                                    36%|█████████████████████▉                                    36%|██████████████████████                                    37%|██████████████████████▎                                   37%|██████████████████████▍                                   37%|██████████████████████▋                                   37%|██████████████████████▊                                   38%|███████████████████████                                   38%|███████████████████████▏                                  38%|███████████████████████▍                                  39%|███████████████████████▋                                  39%|███████████████████████▊                                  39%|████████████████████████                                  40%|████████████████████████▏                                 40%|████████████████████████▍                                 40%|████████████████████████▌                                 41%|████████████████████████▊                                 41%|████████████████████████▉                                 41%|█████████████████████████▏                                42%|█████████████████████████▎                                42%|█████████████████████████▌                                42%|█████████████████████████▊                                43%|█████████████████████████▉                                43%|██████████████████████████▏                               43%|██████████████████████████▎                               43%|██████████████████████████▌                               44%|██████████████████████████▋                               44%|██████████████████████████                                44%|██████████████████████████▏                               45%|███████████████████████████▎                              45%|███████████████████████████▍                              45%|███████████████████████████▋                              46%|███████████████████████████▉                              46%|████████████████████████████                              46%|███████████████████████████▎                              47%|████████████████████████████▍                             47%|███████████████████████████▋                              47%|███████████████████████████▉                              48%|████████████████████████████                              48%|█████████████████████████████▏                            48%|█████████████████████████████▍                            49%|█████████████████████████████▋                            49%|█████████████████████████████▊                            49%|██████████████████████████████                            50%|██████████████████████████████▏                           50%|██████████████████████████████▍                           50%|██████████████████████████████▌                           50%|██████████████████████████████▊                           51%|██████████████████████████████▉                           51%|███████████████████████████████▏                          51%|███████████████████████████████▎                          52%|███████████████████████████████▌                          52%|███████████████████████████████▊                          52%|███████████████████████████████▉                          53%|████████████████████████████████▏                         53%|████████████████████████████████▎                         53%|████████████████████████████████▌                         54%|████████████████████████████████▋                         54%|████████████████████████████████▉                         54%|█████████████████████████████████                         55%|████████████████████████████████▏                         55%|█████████████████████████████████▌                        55%|█████████████████████████████████▋                        56%|█████████████████████████████████▉                        56%|██████████████████████████████████                        56%|██████████████████████████████████▎                       57%|██████████████████████████████████▍                       57%|██████████████████████████████████▋                       57%|██████████████████████████████████▊                       57%|███████████████████████████████████                       58%|███████████████████████████████████▏                      58%|███████████████████████████████████▍                      58%|███████████████████████████████████▋                      59%|███████████████████████████████████▊                      59%|████████████████████████████████████                      59%|████████████████████████████████████▏                     60%|████████████████████████████████████▍                     60%|████████████████████████████████████▌                     60%|████████████████████████████████████▊                     60%|████████████████████████████████████▊                        | 190/315 [33:52<22:16, 10.70s/it]
Traceback (most recent call last):
  File "main.py", line 282, in <module>
    processor.start()
  File "main.py", line 122, in start
    test_wer = seq_eval(self.arg, self.data_loader["test"], self.model, self.device,
  File "/home/muhiddin/SlowFastSign/seq_scripts.py", line 64, in seq_eval
    for batch_idx, data in enumerate(tqdm(loader, ncols=100)):
  File "/home/muhiddin/miniconda3/envs/sfs1/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/muhiddin/miniconda3/envs/sfs1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/muhiddin/miniconda3/envs/sfs1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/muhiddin/miniconda3/envs/sfs1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/muhiddin/miniconda3/envs/sfs1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/muhiddin/SlowFastSign/dataset/dataloader_video.py", line 48, in __getitem__
    input_data, label, fi = self.read_video(idx)
  File "/home/muhiddin/SlowFastSign/dataset/dataloader_video.py", line 121, in read_video
    return [cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB) for img_path in img_list], label_list, fi
  File "/home/muhiddin/SlowFastSign/dataset/dataloader_video.py", line 121, in <listcomp>
    return [cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB) for img_path in img_list], label_list, fi
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Please give your solutions!

**Comment by junseok520** [comment]
In the error message, !_src.empty() seems to mean that the image failed to load. Check the image file path corresponding to the idx where the error occurs and see if the image loaded properly.

Thank you.
